# Generated by Django 6.0.6 on 2026-06-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "-created_at"], name="core_projec_user_id_178de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "-created_at"], name="core_task_user_id_d840c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "-updated_at"], name="core_task_user_id_f8f25f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "-start_time"], name="core_timelo_user_id_0ae5d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "end_time"], name="core_timelo_user_id_df7756_idx"
            ),
        ),
    ]
