# Generated by Django 6.0.6 on 2026-06-30 11:56

from django.db import migrations


def link_subtask_logs_to_tasks(apps, schema_editor):
    TimeLog = apps.get_model('core', 'TimeLog')
    logs = TimeLog.objects.filter(task__isnull=True, subtask__isnull=False).select_related('subtask')
    for log in logs:
        log.task = log.subtask.task
        log.save()

def reverse_link(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_core_projec_user_id_178de8_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(link_subtask_logs_to_tasks, reverse_link),
    ]
