# Generated by Django 6.0.6 on 2026-07-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_populate_timelog_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Activo"), ("COMPLETED", "Completado")],
                default="ACTIVE",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
