# Generated by Django 6.0.6 on 2026-08-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción (Markdown)"),
        ),
    ]
