# Generated by Django 6.0.6 on 2026-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_subtask_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("IN_PROGRESS", "En Progreso"),
                    ("TESTING", "En pruebas"),
                    ("COMPLETED", "Completada"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
