upstream tareas_app {
    server unix:/tmp/tareas.sock fail_timeout=0;
}

server {
    listen 80;
    server_name tareas.srvdebian;

    client_max_body_size 10M;

    location /static/ {
        alias /home/kike/proyectos/tareas/staticfiles/;
    }

    location /media/ {
        alias /home/kike/proyectos/tareas/media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/tmp/tareas.sock;
    }
}
